### PR TITLE
Add the butcher suit

### PR DESCRIPTION
**Pull request by moonysolari**

### CODE REVIEW

**Comment by LennardF1989** [comment]
LGTM

**Review by AnthonyFuller — CHANGES_REQUESTED** [review]
I don't really see a need for this, this image is already in the pack, this is pointlessly copying it.

It's an un-released suit, therefore we don't support it and any fixes that come with it.

**Review by RDIL — APPROVED** [review]

**Comment by RDIL** [comment]
Already in the pack? Where?

**Comment by moonysolari** [comment]
> It's an un-released suit, therefore we don't support it

Well I think it showing up in Peacock in the inventory means that we choose to include it and support it, or else it should be filtered out as a broken item.

**Review by AnthonyFuller — APPROVED** [review]
Turns out it's in the game files, not the image pack, could've sworn it was. Since it's shown in the inventory, we might as well fix this mistake made by IOI as people do use it and will want it kept.

Just hurry up and release it IOI, probably will have to wait until October though, lets be honest.

**Pull request merged**
